import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>rosetta-demo-server</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Rosetta Demo Server</h1>
        <h2>Endpoints</h2>
        <ul>
          <li><code>GET **/supportedLanguages</code></li>
          <li><code>POST **/translate</code></li>
        </ul>
        <h2>Translation Providers</h2>
        <ul>
          <li><code>/api/legacy/**</code></li>
          <ul>
          <li>Uses <a href="https://github.com/vitalets/google-translate-api">@vitalets/google-translate-api</a>, a reverse engineered wrapper of the translate.google.com API, with Firebase Firestore caching.</li>
          </ul>
          <li><code>/api/v2/**</code></li>
          <ul>
            <li>Uses <a href="https://cloud.google.com/translate/docs/reference/libraries/v2/overview-v2">Google Cloud Translation API (Basic)</a> with Firebase Firestore caching.</li>
          </ul>
          <li><code>/api/v3/**</code></li>
          <ul>
            <li>Uses <a href="https://cloud.google.com/translate/docs/reference/libraries/v3/overview-v3">Google Cloud Translation API (Advanced)</a> with Firebase Firestore caching.</li>
          </ul>
          <li><code>/api/msft/**</code></li>
          <ul>
            <li>Uses <a href="https://docs.microsoft.com/en-us/azure/cognitive-services/translator/">Microsoft Translator API</a> with Firebase Firestore caching.</li>
          </ul>
        </ul>
        <h2>Caching</h2>
        <p>Check the <code>X-Translation-Cache-Hit-Count</code> and <code>X-Translation-Cache-Miss-Count</code> to see how many strings were cached and not cached respectively.</p>
        <h2>Inspect Cache Ratio</h2>
        <p>You can inspect the cache ratio <Link href="/cache"><a>here</a></Link></p>
      </main>

      <footer className={styles.footer}>
        <p><a href="https://github.com/au5ton/rosetta-demo-server">Source Code</a>, intended to be paired with <a href="https://github.com/au5ton/rosetta">Rosetta</a>.</p>
      </footer>
    </div>
  )
}
